### ISSUE TITLE
custom_id is not passed to stripe for plan with free trial period

### ISSUE THREAD

**Issue by minghiu** [moonclerk/developer#6]
Hi, I am following the document here to passing a cid into my payment url. I can see the custom_id is passed to the successful payment url redirect but i am not be able to find it in stripe meta data. Please resolve the problem. Thanks.

**Comment by ryanmccrary** [comment]
Hi @minghiu - thanks for reaching out.

Since this is just our documentation site I'm going to close this issue and ask that you contact help@moonclerk.com so that we can better assist.

When you reach out, please include you account email, the form and plan that you are having issues with so we can more quickly investigate the issue.

**Comment by minghiu** [comment]
Hi Ryan,

I have contacted help@moonclerk.com however your support staff Tara Cash
told me they don't provide support for this feature. So I had to come here
to seek for help.

**Comment by mbbertino** [comment]
Hello @minghiu, 

We've been able to access your support inquiries. The short answer is everything seems to set up correctly and is showing in Stripe. 

But due to sensitive information we'll be reaching back out through existing inquiries with a more detailed response.
